== Contribute

== Contributing to Dirac

First off, thanks for taking the time to contribute! ❤️

All types of contributions are encouraged and valued. See the
link:#table-of-contents[Table of Contents] for different ways to help
and details about how this project handles them. Please make sure to
read the relevant section before making your contribution. It will make
it a lot easier for us maintainers and smooth out the experience for all
involved. The community looks forward to your contributions. 🎉

____
And if you like the project, but just don’t have time to contribute,
that’s fine. There are other easy ways to support the project and show
your appreciation, which we would also be very happy about: - Star the
project - Post about it - Refer this project in your project’s readme -
Mention the project at local meetups and tell your friends/colleagues
____

=== Table of Contents

* link:#code-of-conduct[Code of Conduct]
* link:#i-have-a-question[I Have a Question]
* link:#i-want-to-contribute[I Want To Contribute]
** link:#reporting-bugs[Reporting Bugs]
** link:#suggesting-enhancements[Suggesting Enhancements]
** link:#your-first-code-contribution[Your First Code Contribution]
** link:#improving-the-documentation[Improving The Documentation]
* link:#styleguides[Styleguides]
** link:#commit-messages[Commit Messages]
* link:#join-the-project-team[Join The Project Team]

=== Code of Conduct

This project and everyone participating in it is governed by the
https://github.com/tom65536/dirac/blob/master/CODE_OF_CONDUCT.md[Dirac
Code of Conduct]. By participating, you are expected to uphold this
code. Please report unacceptable behavior to peregrinus@planet.ms.

=== I Have a Question

____
If you want to ask a question, we assume that you have read the
available https://tom65536.github.io/dirac/[Documentation].
____

Before you ask a question, it is best to search for existing
https://github.com/tom65536/dirac/issues[Issues] that might help you. In
case you have found a suitable issue and still need clarification, you
can write your question in this issue. It is also advisable to search
the internet for answers first.

If you then still feel the need to ask a question and need
clarification, we recommend the following:

* Open an https://github.com/tom65536/dirac/issues/new[Issue].
* Provide as much context as you can about what you’re running into.
* Provide project and platform versions, depending on what seems
relevant.

We will then take care of the issue as soon as possible.

=== I Want To Contribute

____
==== Legal Notice

When contributing to this project, you must agree that you have authored
100% of the content, that you have the necessary rights to the content
and that the content you contribute may be provided under the project
license.
____

____
==== Be FAIR

This project adopts and implements the
https://rd-alliance.org/group/fair-research-software-fair4rs-wg/outcomes/fair-principles-research-software-fair4rs-0[FAIR
for Research Software principles]
https://doi.org/10.15497/RDA00068[(DOI:10.15497/RDA00068)]. If your
contribution relies on your or other people’s research, please, make
sure you inicate the appropriate references in the
https://github.com/tom65536/dirac/blob/master/codemeta.json[codemeta.json]
file (see https://codemeta.github.io/[The CodeMeta Project] for
reference).
____

==== Reporting Bugs

===== Before Submitting a Bug Report

A good bug report shouldn’t leave others needing to chase you up for
more information. Therefore, we ask you to investigate carefully,
collect information and describe the issue in detail in your report.
Please complete the following steps in advance to help us fix any
potential bug as fast as possible.

* Make sure that you are using the latest version.
* Determine if your bug is really a bug and not an error on your side
e.g. using incompatible environment components/versions (Make sure that
you have read the https://tom65536.github.io/dirac/[documentation]. If
you are looking for support, you might want to check
link:#i-have-a-question[this section]).
* To see if other users have experienced (and potentially already
solved) the same issue you are having, check if there is not already a
bug report existing for your bug or error in the
https://github.com/tom65536/dirac/issues?q=label%3Abug[bug tracker].
* Also make sure to search the internet (including Stack Overflow) to
see if users outside of the GitHub community have discussed the issue.
* Collect information about the bug:
** Stack trace (Traceback)
** OS, Platform and Version (Windows, Linux, macOS, x86, ARM)
** Version of the interpreter, compiler, SDK, runtime environment,
package manager, depending on what seems relevant.
** Possibly your input and the output
** Can you reliably reproduce the issue? And can you also reproduce it
with older versions?

===== How Do I Submit a Good Bug Report?

____
You must never report security related issues, vulnerabilities or bugs
including sensitive information to the issue tracker, or elsewhere in
public. Instead sensitive bugs must be sent by email to
peregrinus@planet.ms.
____

We use GitHub issues to track bugs and errors. If you run into an issue
with the project:

* Open an https://github.com/tom65536/dirac/issues/new[Issue]. (Since we
can’t be sure at this point whether it is a bug or not, we ask you not
to talk about a bug yet and not to label the issue.)
* Explain the behavior you would expect and the actual behavior.
* Please provide as much context as possible and describe the
_reproduction steps_ that someone else can follow to recreate the issue
on their own. This usually includes your code. For good bug reports you
should isolate the problem and create a reduced test case.
* Provide the information you collected in the previous section.

Once it’s filed:

* The project team will label the issue accordingly.
* A team member will try to reproduce the issue with your provided
steps. If there are no reproduction steps or no obvious way to reproduce
the issue, the team will ask you for those steps and mark the issue as
`needs-repro`. Bugs with the `needs-repro` tag will not be addressed
until they are reproduced.
* If the team is able to reproduce the issue, it will be marked
`needs-fix`, as well as possibly other tags (such as `critical`), and
the issue will be left to be
link:#your-first-code-contribution[implemented by someone].

==== Suggesting Enhancements

This section guides you through submitting an enhancement suggestion for
Dirac, *including completely new features and minor improvements to
existing functionality*. Following these guidelines will help
maintainers and the community to understand your suggestion and find
related suggestions.

===== Before Submitting an Enhancement

* Make sure that you are using the latest version.
* Read the link:[documentation] carefully and find out if the
functionality is already covered, maybe by an individual configuration.
* Perform a https://github.com/tom65536/dirac/issues[search] to see if
the enhancement has already been suggested. If it has, add a comment to
the existing issue instead of opening a new one.
* Find out whether your idea fits with the scope and aims of the
project. It’s up to you to make a strong case to convince the project’s
developers of the merits of this feature. Keep in mind that we want
features that will be useful to the majority of our users and not just a
small subset. If you’re just targeting a minority of users, consider
writing an add-on/plugin library.

===== How Do I Submit a Good Enhancement Suggestion?

Enhancement suggestions are tracked as
https://github.com/tom65536/dirac/issues[GitHub issues].

* Use a *clear and descriptive title* for the issue to identify the
suggestion.
* Provide a *step-by-step description of the suggested enhancement* in
as many details as possible.
* *Describe the current behavior* and *explain which behavior you
expected to see instead* and why. At this point you can also tell which
alternatives do not work for you.
* You may want to *include screenshots and animated GIFs* which help you
demonstrate the steps or point out the part which the suggestion is
related to. You can use https://www.cockos.com/licecap/[this tool] to
record GIFs on macOS and Windows, and
https://github.com/colinkeenan/silentcast[this tool] or
https://github.com/GNOME/byzanz[this tool] on Linux.
* *Explain why this enhancement would be useful* to most Dirac users.
You may also want to point out the other projects that solved it better
and which could serve as inspiration.

==== Your First Code Contribution

* This project does not enforce a specific IDE but you are encouraged to
set up your editor to respect the settings of the
https://github.com/tom6536/dirac/blob/master/.editorconfig[`.editorconfig`]
file. See the https://editorconfig.org/[EditorConfig] site for a list of
IDEs, editors and plugins.
* Some of the style rules are enforced by
https://pre-commit.com/[Pre-Commit] hooks. You are encouraged to install
pre-commit locally such that these rules are checked ech time you
commit.
* Your development environment needs a recent Java development kit, a C
compiler and a working LaTeX installation, at least providing the CWEB
literate programming tools.

=== Styleguides

==== Commit Messages

* Commit atomic changes, do not commit unrelated changes in a single
commit.
* Keep your commit messages short.
* Use imperative mood (prsent tense) for commit messages: ``change'' not
``changed'' nor ``changes''
* Don’t capitalize the first letter
* No dot (.) at the end
* If you work on an issue make reference to it.
* Make sure all pre-commit hooks succeed before you commit
* Apply
https://www.conventionalcommits.org/en/v1.0.0/#specification[Conventional
Commits Format (1.0.0)] as we would like to exploit commit messages for
https://github.com/semantic-release/semantic-release[Semantic Release]
workflow.

A commit message should therefore have the following
https://github.com/angular/angular/blob/main/CONTRIBUTING.md#-commit-message-format[Angular
Commit Format]:

....
<type>(<optional scope>): <short summary>

<optional body>

<optional footer>
....

The possible scopes for this project are the names of the sub-packages
or `repo` for changes affecting repository metadata, i.e. especially
_NOT_ affecting any of the sub-packages directly.

Example:

....
feat(java): add command line option for verbosity

Add a command line option `--verbose` (short: `-v`)
which makes the program print out all HTTP requests
to standard output.


Fixes #2587
....

There are several things to avoid in commit messages:

* Do NOT include any secrets such as passwords or TLS keys in the
message.
* Do NOT include anything that you wouldn’t want published in a
newspaper. Usually messages can be read by others.
* Avoid massive sizes.

For further information you might want to read the introductory blog
post
https://initialcommit.com/blog/git-commit-messages-best-practices[Git
Commit Messages: Best Practices & Guidelines] by Matthew Forsyth.

=== Attribution

This guide is based on the *contributing-gen*.
https://github.com/bttger/contributing-gen[Make your own]!
