/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hep.dirac.app;

import  hep.dirac.model.UFOModel;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello, Dirac");
    }
}
