/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hep.dirac.impl;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class DiracNativeTest {
    @Test void testConstructor() {
        //assertEquals(0, list.size());
    }
}
